# Quick wrap

In [1]:
from sklearn.cluster import KMeans

In [4]:
import numpy as np

In [12]:
X = np.array([[1,0],[1,1],[1,2],
             [10,0],[10,1],[10,2]])

In [25]:
X

array([[ 1,  0],
       [ 1,  1],
       [ 1,  2],
       [10,  0],
       [10,  1],
       [10,  2]])

# Model build and Predict

In [14]:
model = KMeans(n_clusters=2)
model.fit(X)

KMeans(n_clusters=2)

In [24]:
model.cluster_centers_

array([[ 1.,  1.],
       [10.,  1.]])

In [16]:
model.predict([[0,0]])

array([0])

In [23]:
model.predict([[5.5,0]])

array([0])

In [22]:
model.predict([[5.6,0]])

array([1])

In [18]:
model.predict([[10,0]])

array([1])